# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebb443090ae41d0a93611166cdfff1453d22f7b8c28624e8461e8855c010aff766b830a9ef2585bfd76eb1dd1135a84ba80edc16ad11183d34a0146e43a295da

test:
  secret_key_base: dd6e7c288c4fae9bf20f9abde852f43b057ed9455faa4e81be60e7d54ff94e35f8e2c897c518babc13efbb4ed64e9ca0e510b7186b32d12802e02eb6f01c9a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
